import { GetStaticProps } from 'next'
import Head from 'next/head'
import About from '../components/About'
import ContactMe from '../components/ContactMe'
import Education from '../components/Education'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import { PageInfo, Project, Skill, Social } from '../typings'
import { fetchPageInfo } from '../utils/fetchPageInfo'
import { fetchProjects } from '../utils/fetchProjects'
import { fetchSkills } from '../utils/fetchSkills'
import { fetchSocial } from '../utils/fetchSocials'

type Props = {
  pageInfo: PageInfo;
  skills: Skill[];
  projects: Project[];
  socials: Social[];
}

const Home = ({pageInfo, skills, projects, socials}: Props) => {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll 
    overflow-x-hidden z-0 scrollbar-thin scrollbar-track-gray-400/20 scrollbar-thumb-[#f2aa4cff]/80'>
      <Head>
        <title>Anand&#39;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header socials={socials} />
      {/* Hero */}
      <section id='hero' className='snap-start'>
        <Hero pageInfo={pageInfo} />
      </section>
      {/* About */}
      <section id='about' className='snap-center'>
        <About pageInfo={pageInfo} />
      </section>
      {/* Education */}
      <section id='education' className='snap-center'>
        <Education />
      </section>
      {/* Skills */}
      <section id='skills' className='snap-start'>
        <Skills skills={skills} />
      </section>
      {/* Projects */}
      <section id='projects' className='snap-start'>
        <Projects projects={projects} />
      </section>
      {/* Contact me */}
      <section id='contact' className='snap-start'>
        <ContactMe pageInfo={pageInfo} />
      </section>
    </div>
  )
}

export default Home;

export const getStaticProps: GetStaticProps<Props> = async() => {
  const pageInfo: PageInfo = await fetchPageInfo();
  const skills: Skill[] = await fetchSkills();
  const projects: Project[] = await fetchProjects();
  const socials: Social[] = await fetchSocial();
  return {
    props: {
      pageInfo,
      skills,
      projects,
      socials,
    },
    //nextjs will attempt to re-generate the page:
    //- When a request comes in
    //- At most once every 10 seconds
    revalidate: 10,
  };
};
